In [1]:
import numpy as np

Change the below joint variables to get the entire Jacobian matrix.

In [2]:
l1=1
l2=1
l3=1

q1=0
q2=0
q3=0

The code below is doing all the calculations!

In [4]:
O0=np.array([[0],
             [0],
             [0]])

R01=np.array([[np.cos(q1), -np.sin(q1), 0],
              [np.sin(q1), np.cos(q1), 0],
              [0, 0, 1]])
d01=np.array([[0],
             [0],
             [0]])
R12=np.array([[np.cos(q2), -np.sin(q2), 0],
              [np.sin(q2), np.cos(q2), 0],
              [0, 0, 1]])
d12=np.array([[l1],
             [0],
             [0]])
R23=np.array([[np.cos(q3), -np.sin(q3), 0],
              [np.sin(q3), np.cos(q3), 0],
              [0, 0, 1]])
d23=np.array([[l2],
             [0],
             [0]])

lastrow=np.array([[0,0,0,1]])

temp=np.concatenate((R01,d01),axis=1)
H01=np.concatenate((temp,lastrow),axis=0)

temp=np.concatenate((R12,d12),axis=1)
H12=np.concatenate((temp,lastrow),axis=0)

temp=np.concatenate((R23,d23),axis=1)
H23=np.concatenate((temp,lastrow),axis=0)

p1=np.array([[l1],
             [0],
             [0],
             [1]])
p2=np.array([[l2],
             [0],
             [0],
             [1]])
p3=np.array([[l3],
             [0],
             [0],
             [1]])
O1=(H01@p1)[:-1]
O2=(H01@H12@p2)[:-1]
O3=(H01@H12@H23@p3)[:-1]

z0=np.array([[0],
             [0],
             [1]])
z1=R01@z0
z2=R12@z1

j1=np.cross(z0.T,(O3-O0).T)
j2=np.cross(z1.T,(O3-O1).T)
j3=np.cross(z2.T,(O3-O2).T)
jv=np.concatenate((j1.T,j2.T,j3.T),axis=1)
jw=np.concatenate((z0,z1,z2),axis=1)
# jw=np.concatenate((np.concatenate((z0,[[0]]),axis=0),np.concatenate((z1,[[0]]),axis=0),np.concatenate((z2,[[0]]),axis=0)),axis=1)
j=np.concatenate((jv,jw),axis=0)
print(j)

[[0. 0. 0.]
 [3. 2. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]]
