In [27]:
import numpy as np

l1 = 1
l2 = 1
l3 = 1
theta1 = np.pi/4
theta2 = np.pi/2
d = 1

R01 = np.array([[np.cos(theta1), -np.sin(theta1), 0],[np.sin(theta1), np.cos(theta1), 0],[0, 0, 1]])
d01 = np.array([[l2*np.cos(theta1)],[l2*np.sin(theta1)],[l1]])
R12 = np.array([[np.cos(theta2), np.sin(theta2), 0],[np.sin(theta1), -np.cos(theta1), 0],[0, 0, -1]])
d12 = np.array([[l3*np.cos(theta2)],[l3*np.sin(theta2)],[0]])
R23 = np.array([[1, 0, 0],[0, 1, 0],[0, 0, 1]])
d23 = np.array([[0],[0],[d]])

H01 = np.hstack((R01,d01))
H01 = np.vstack((H01, np.array([0, 0, 0, 1])))
H12 = np.hstack((R12,d12))
H12 = np.vstack((H12, np.array([0, 0, 0, 1])))
H23 = np.hstack((R23,d23))
H23 = np.vstack((H23, np.array([0, 0, 0, 1])))
H02 = np.matmul(H01, H12)
H03 = np.matmul(H02, H23)

p1 = 1
p2 = 1
p3 = 0

z0 = np.array([[0,0,1]])
z1 = z0
z2 = -z0

o0 = np.array([[0,0,0]])
o = np.array([[0],[0],[0],[1]])
o1 = np.matmul(H01, o)[0:3]
o2 = np.matmul(H02, o)[0:3]
o3 = np.matmul(H03, o)[0:3]
o1 = np.reshape(o1, (1,3))
o2 = np.reshape(o2, (1,3))
o3 = np.reshape(o3, (1,3))

Jw1 = p1*z0
Jw2 = p2*z1
Jw3 = p3*z2
Jv1 = np.cross(z0, (o3-o0))
Jv2 = np.cross(z1, (o3-o1))
Jv3 = np.cross(z2, (o3-o2))
Jw1 = np.reshape(Jw1, (3,1))
Jw2 = np.reshape(Jw2, (3,1))
Jw3 = np.reshape(Jw3, (3,1))
Jv1 = np.reshape(Jv1, (3,1))
Jv2 = np.reshape(Jv2, (3,1))
Jv3 = np.reshape(Jv3, (3,1))

J1 = np.vstack((Jv1, Jw1))
J2 = np.vstack((Jv2, Jw2))
J3 = np.vstack((Jv3, Jw3))

temp = np.hstack((J1, J2))
J = np.hstack((temp, J3))

print(J)

[[-1.41421356e+00 -7.07106781e-01  0.00000000e+00]
 [ 1.11022302e-16 -7.07106781e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00  0.00000000e+00]]
