Importing Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt

Initializing the Robot


In [2]:
L1 = 5
L2 = 5
L3 = 5
q1 = np.pi/6
q2 = np.pi/3
d = 1

Creating Roation Matrices R and d matrices

In [3]:
R01 = np.array([[np.cos(q1), -np.sin(q1), 0],[np.sin(q1), np.cos(q1), 0],[0, 0, 1]])
d01 = np.array([[L2*np.cos(q1)],[L2*np.sin(q1)],[L1]])
R12 = np.array([[np.cos(q2), np.sin(q2), 0],[np.sin(q1), -np.cos(q1), 0],[0, 0, -1]])
d12 = np.array([[L3*np.cos(q2)],[L3*np.sin(q2)],[0]])
R23 = np.array([[1, 0, 0],[0, 1, 0],[0, 0, 1]])
d23 = np.array([[0],[0],[d]])

Creating homogenous matrices form R and d

In [4]:
H01 = np.hstack((R01,d01))
H01 = np.vstack((H01, np.array([0, 0, 0, 1])))
H12 = np.hstack((R12,d12))
H12 = np.vstack((H12, np.array([0, 0, 0, 1])))
H23 = np.hstack((R23,d23))
H23 = np.vstack((H23, np.array([0, 0, 0, 1])))
H02 = np.matmul(H01, H12)
H03 = np.matmul(H02, H23)

Defining z terms for Jw

In [5]:
Rho_1 = 1
Rho_2 = 1
Rho_3 = 0

z0 = np.array([[0,0,1]])
z1 = z0
z2 = -z0

Defining O terms for Jv

In [6]:
O_0 = np.array([[0,0,0]])
O_matrix = np.array([[0],[0],[0],[1]])
O_1 = np.matmul(H01, O_matrix)[0:3]
O_2 = np.matmul(H02, O_matrix)[0:3]
O_3 = np.matmul(H03, O_matrix)[0:3]
O_1 = np.reshape(O_1, (1,3))
O_2 = np.reshape(O_2, (1,3))
O_3 = np.reshape(O_3, (1,3))

Compiling Jw and Jv matrices

In [7]:
Jw1 = Rho_1*z0
Jw2 = Rho_2*z1
Jw3 = Rho_3*z2

Jv1 = np.cross(z0, (O_3-O_0))
Jv2 = np.cross(z1, (O_3-O_1))
Jv3 = np.cross(z2, (O_3-O_2))

Jw1 = np.reshape(Jw1, (3,1))
Jw2 = np.reshape(Jw2, (3,1))
Jw3 = np.reshape(Jw3, (3,1))

Jv1 = np.reshape(Jv1, (3,1))
Jv2 = np.reshape(Jv2, (3,1))
Jv3 = np.reshape(Jv3, (3,1))

Printing final Jacobian Matrix

In [8]:
J1 = np.vstack((Jv1, Jw1))
J2 = np.vstack((Jv2, Jw2))
J3 = np.vstack((Jv3, Jw3))

temp = np.hstack((J1, J2))
J = np.hstack((temp, J3))

print(J)

[[-7.50000000e+00 -5.00000000e+00  0.00000000e+00]
 [ 4.33012702e+00  8.88178420e-16  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00  0.00000000e+00]]
