In [73]:
import numpy as np

# Input

In [81]:
matrix=[]

n=int(input("No. of links: "))
sym=["a","alpha","d","theta"]
for i in range(n):
  a=[]
  for j in range(4):
    a.append(float(input(f"Link-{i+1},{sym[j]} : ")))
  matrix.append(a)
  print("\n")

matrix

No. of links: 3
Link-1,a : 1
Link-1,alpha : 0
Link-1,d : 0
Link-1,theta : 1


Link-2,a : 1
Link-2,alpha : 0
Link-2,d : 0
Link-2,theta : 1


Link-3,a : 1
Link-3,alpha : 0
Link-3,d : 0
Link-3,theta : 1




[[1, 0, 0, 1], [1, 0, 0, 1], [1, 0, 0, 1]]

# D-H Transformation Matrix Function

In [75]:
def dh(arr):
  a=arr[0]
  alpha=arr[1]
  d=arr[2]
  theta = arr[3]

  mat = []
  b=[np.cos(theta), -np.sin(theta)*np.cos(alpha), np.sin(theta)*np.sin(alpha), a*np.cos(theta)]
  mat.append(b)

  b=[np.sin(theta), np.cos(theta)*np.cos(alpha), -np.cos(theta)*np.sin(alpha), a*np.sin(theta)]
  mat.append(b)

  b=[0, np.sin(alpha), np.cos(alpha), d]
  mat.append(b)

  b=[0,0,0,1]
  mat.append(b)

  return np.matrix(mat)

In [82]:
dh(matrix[1])

matrix([[ 0.54030231, -0.84147098,  0.        ,  0.54030231],
        [ 0.84147098,  0.54030231, -0.        ,  0.84147098],
        [ 0.        ,  0.        ,  1.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]])

#Transformation Matrix

In [83]:
T = np.identity(4)
Tmat = []
for i in range(n):
  T=np.matmul(T,dh(matrix[i]))
  Tmat.append(T)
print(f"Transformation Matrix (0-{n}) : \n\n{T}")

Transformation Matrix (0-3) : 

[[-0.9899925  -0.14112001  0.         -0.86583703]
 [ 0.14112001 -0.9899925   0.          1.89188842]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]


#End effector Position

In [84]:
pos6=np.matrix([0,0,0,1])
Pos = np.matmul(Tmat[-1],pos6.T)
print(f"Position (0): \n\n{Pos[:3]}")


Position (0): 

[[-0.86583703]
 [ 1.89188842]
 [ 0.        ]]


# Determining Z-axes and origins for each Joint


In [85]:
z=[]
z.append(np.matrix([0,0,1]).T)

p=[]
p.append(np.matrix([0,0,0]).T)

for a in Tmat:
  z.append(a[:3,2])
  p.append(a[:3,3])
p

[matrix([[0],
         [0],
         [0]]), matrix([[0.54030231],
         [0.84147098],
         [0.        ]]), matrix([[0.12415547],
         [1.75076841],
         [0.        ]]), matrix([[-0.86583703],
         [ 1.89188842],
         [ 0.        ]])]

#Jecobinan Matrix

In [86]:
J = np.cross(z[0].T,(p[-1]-p[0]).T).T
J = np.concatenate((J,z[0]),axis=0)

for i in range (1,len(z)-1):
  x = np.cross(z[i].T,(p[-1]-p[i]).T).T
  x = np.concatenate((x,z[i]),axis=0)
  J = np.concatenate((J,x),axis=1)
print(f"Jecobian Matrix :\n\n{J}") 

Jecobian Matrix :

[[-1.89188842 -1.05041743 -0.14112001]
 [-0.86583703 -1.40613933 -0.9899925 ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 1.          1.          1.        ]]
