In [1]:
import numpy as np

In [23]:
q1=int(input("q1 :"))
q2=int(input("q2 :"))
d=int(input("d :"))


q1 :1
q2 :1
d :1


In [24]:
R01=np.matrix([[np.cos(q1),-np.sin(q1),0],[np.sin(q1),np.cos(q1),0],[0,0,1]])

d01=np.matrix([0,0,0])

H01 = np.concatenate((R01,d01.T),axis = 1)
a=np.matrix([[0,0,0,1]])
H01=np.concatenate((H01,a),axis=0)

print(H01)


R12=np.matrix([[np.cos(q2),-np.sin(q2),0],[np.sin(q2),np.cos(q2),0],[0,0,1]])

d12=np.matrix([1,0,0])

H12 = np.concatenate((R12,d12.T),axis = 1)

H12=np.concatenate((H12,a),axis=0)

print(H12)


R23=np.matrix([[np.cos(np.pi/2),0,np.sin(np.pi/2)],[0,1,0],[-np.sin(np.pi/2),0,np.cos(np.pi/2)]])

d23=np.matrix([1,0,0])

H23 = np.concatenate((R23,d23.T),axis = 1)

H23=np.concatenate((H23,a),axis=0)

print(H23)

[[ 0.54030231 -0.84147098  0.          0.        ]
 [ 0.84147098  0.54030231  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]
[[ 0.54030231 -0.84147098  0.          1.        ]
 [ 0.84147098  0.54030231  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]
[[ 6.123234e-17  0.000000e+00  1.000000e+00  1.000000e+00]
 [ 0.000000e+00  1.000000e+00  0.000000e+00  0.000000e+00]
 [-1.000000e+00  0.000000e+00  6.123234e-17  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]


In [25]:
p3=np.matrix([[1+d],[0],[0],[1]])

p0=np.matmul(H01,H12)
p0=np.matmul(p0,H23)
p0=np.matmul(p0,p3)

print("Final position vector in frame 0:")
print(p0[:3])

Final position vector in frame 0:
[[ 0.12415547]
 [ 1.75076841]
 [-2.        ]]
