In [ ]:
import numpy as np

#n = number of links

#omega = an array containg the omega of all the joints

# J_type_ar is an array containing the joint types. For a revolute joint insert 1 and for a prismatic joint.

#dh= a matrix containing dh parameters of all the links in order (-theta,d,a,alpha)

def forward_kinamatics(n,dh,J_type_ar,omega):
  A=[]

  for i in range(1,n+1):
      theta=dh[i-1][0]
      d=dh[i-1][1]
      a=dh[i-1][2]
      alpha=dh[i-1][3]

      theta=theta*(np.pi)/180
      alpha=alpha*(np.pi)/180

      row1 = [np.cos(theta), -np.sin(theta)*np.cos(alpha), np.sin(theta)*np.sin(alpha), a*np.cos(theta)]
      row2 = [np.sin(theta), np.cos(theta)*np.cos(alpha), -np.cos(theta)*np.sin(alpha), a*np.sin(theta)]
      row3 = [0, np.sin(alpha), np.cos(alpha), d]
      row4 = [0, 0 ,0, 1]

      A_i = [row1, row2, row3, row4]
      A = A + [A_i]

  omega=np.transpose(np.array(omega))
  print("omega =",omega)    
  T = ([1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1])
  R = []
  z=[[0,0,1]]
  O=[[0,0,0]]
  for i in range(0,len(A)):
    T=np.dot(T,A[i])
    R_c=[[T[0][0],T[0][1],T[0][2]],[T[1][0],T[1][1],T[1][2]],[T[2][0],T[2][1],T[2][2]]]
    z_c=np.dot(R_c,[[0],[0],[1]])
    z = z+[[z_c[0][0],z_c[1][0],z_c[2][0]]]
    R=R+[R_c]
    O=O+[[T[0][3],T[1][3],T[2][3]]]

  Jv = []
  Jw = []
  for i in range(0+1,n+1):
    if(J_type_ar[i-1]==1):
      J_i=np.cross(np.array(z[i-1]),np.subtract(O[n],O[i-1]))
      Jv = Jv+[J_i]
      Jw = Jw + [z[i-1]]
    elif(J_type_ar[i-1]==0):
      J_i=np.array(z[i-1])
      Jv = Jv+[J_i]
      Jw = Jw + [[0,0,0]]
    else:
      print("please enter only 0 or 1")
      i=i-1

  Jv=np.around(np.transpose(np.array(Jv)),3)
  Jw=np.around(np.transpose(np.array(Jw)),3)
  J=Jv
  J=np.append(J,[np.array(Jw[0])],axis=0)
  J=np.append(J,[np.array(Jw[1])],axis=0)
  J=np.append(J,[np.array(Jw[2])],axis=0)

  vel = np.dot(J,omega)
  print("J = ",np.around(J,3))
  #print("Jv = ",np.around(Jv,3))
  #print("Jw = ",np.around(Jw,3))
  print("Transformation matrix ,T(0,",n,") = \n",np.around(T,3))
  print("End-effector position =",np.around([T[0][3],T[1][3],T[2][3]],3))
  print("End-effector velocity = ",np.transpose(np.around(vel,3)))

print("ASSIGNMENT PROBLEM-4 RRP SCARA VERIFICATION")
n=3
dh =[[45,0,10,0],[90,0,10,0],[0,-25,0,180]]
J_type_ar=[1,1,0]
omega=[15,10,20]
forward_kinamatics(n,dh,J_type_ar,omega)

print("\n")
print("ASSIGNMENT PROBLEM-4 RRP STANFORD VERIFICATION")
n=3
dh =[[45,0,5,0],[-45,0,0,-90],[0,30,0,0]]
J_type_ar=[1,1,0]
omega=[15,10,20]
forward_kinamatics(n,dh,J_type_ar,omega)

print("\n")  
print("ASSIGNMENT PROBLEM-5 VERIFICATION(TEXTBOOK PROBLEM-3.7)")
n=3
dh =[[0,2,0,90],[90,5,0,-90],[0,3,0,0]]
J_type_ar=[0,0,0]
omega=[0,0,0]
forward_kinamatics(n,dh,J_type_ar,omega)

print("\n")
print("ASSIGNMENT PROBLEM-6 VERIFICATION(TEXTBOOK PROBLEM-3.8)")
n=6
dh =[[0,0,0,90],[0,0,3,0],[0,0,3,0],[0,0,0,-90],[90,0,0,90],[0,3,0,0]]
J_type_ar=[1,1,1,1,1,1]
omega=[15,15,15,15,15,15]
forward_kinamatics(n,dh,J_type_ar,omega)


ASSIGNMENT PROBLEM-4 RRP SCARA VERIFICATION
omega = [15 10 20]
J =  [[-14.142  -7.071   0.   ]
 [  0.     -7.071   0.   ]
 [  0.      0.      1.   ]
 [  0.      0.      0.   ]
 [  0.      0.      0.   ]
 [  1.      1.      0.   ]]
Transformation matrix ,T(0, 3 ) = 
 [[ -0.707   0.707   0.      0.   ]
 [  0.707   0.707   0.     14.142]
 [  0.      0.     -1.    -25.   ]
 [  0.      0.      0.      1.   ]]
End-effector position = [  0.     14.142 -25.   ]
End-effector velocity =  [-282.84  -70.71   20.      0.      0.     25.  ]


ASSIGNMENT PROBLEM-4 RRP STANFORD VERIFICATION
omega = [15 10 20]
J =  [[-33.536 -30.      0.   ]
 [  3.536   0.      1.   ]
 [  0.      0.      0.   ]
 [  0.      0.      0.   ]
 [  0.      0.      0.   ]
 [  1.      1.      0.   ]]
Transformation matrix ,T(0, 3 ) = 
 [[ 1.    -0.     0.     3.536]
 [ 0.     0.     1.    33.536]
 [ 0.    -1.     0.     0.   ]
 [ 0.     0.     0.     1.   ]]
End-effector position = [ 3.536 33.536  0.   ]
End-effector velocity =